import Head from "next/head";
import Table from "../components/table";
import SideNav from "../components/sideNav";


export default function Home() {
    return (
    <>
        <Head>
            <title>Admin CSE</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="../public/pro.ico"/>
        </Head>
        <main className=" flex w-screen gap-10 ">
            <div className="container w-fit">
                <SideNav/>
            </div>


            <div className="container">
                <Table/>
            </div>

        </main>
    </>
    );
}
