import Head from "next/head";
import Table from "../components/table";
import SideNav from "../components/sideNav";


export default function Home() {
    return (
    <>
        <Head>
            <title>Admin CSE</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="../public/pro.ico"/>
        </Head>
        <main className="py-5">

            <div className="container mx-auto flex justify-between py-1 border-b">
                </div>
            <div className="container mx-auto">
                <SideNav/>
            </div>



            <div className="container mx-auto">
                <Table/>
            </div>

        </main>
    </>
    );
}
